DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BINARY(16) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'USER',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id)
);
